<ul class="footer links">
<li class="nav items">
    <a href="http://www.google.com">Google</a>
    <span><br>Go to google.com to know our popularity</span>
</li>
<li class="nav items">
    <a href="http://www.facebook.com">Facebook</a>
    <span><br>Go to facebook and follow us</span>
</li>
<li class="nav items">
    <a href="http://www.w3schools.com">W3 Schools</a>
    <span><br>Become a developer and join us..</span>
</li>
<li class="nav items">
    <a href="offers">Offers</a>
    <span><br>Your must visit page</span>
</li>
</ul>
